### PR TITLE
translate new

### PR DESCRIPTION
**Pull request by liyoubdu**

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by liyoubdu** [comment]
how about my #159 pull request ?

**Comment by ciampix** [comment]
Ah sorry I forgot it and so merged in the wrong order so I am afraid you now have to update it because now it conflict with the newer approved patch. Please do not ask for a pull request while there is another pending for the same file(s) to avoid this problem or just rebase the older conflicting patch in order to update it to the current state of the branch... thanks!

**Comment by liyoubdu** [comment]
ok, i have resolved conflict for #159 pull request.

**Comment by ciampix** [comment]
Ok so may I close the #159?

**Comment by liyoubdu** [comment]
why not merge #159?

**Comment by liyoubdu** [comment]
i think you can merge #159. and then close it.

**Comment by ciampix** [comment]
Because it states: "This branch has conflicts that must be resolved" so I cannot merge it without brake the compilation... you have to rebase or prepare another patch (and I close this). I'm sorry.

**Comment by liyoubdu** [comment]
but now there is no conflict in #159.

**Comment by liyoubdu** [comment]
sorry, conflicts still display. you can close it. later i will create new pull request.

**Comment by ciampix** [comment]
ok thanks!

**Pull request merged**
