### PR TITLE
[de] fix translation Mode -> Modus instead of Farbmodus 

### PR DESCRIPTION
**Pull request by pointhi**
I do not think "Farbmodus" is the correct term

### CODE REVIEW

**Comment by ciampix** [comment]
Perhaps "Modalität"? Entschuldigen Sie, ich spreche kein Deutsch...

**Comment by pointhi** [comment]
nope, "Modalität" is also a german word not really representing what this does. "Modus" should be the correct and easiest term.

**Comment by pointhi** [comment]
a better term could be "Routing Modus", which also tells what this mode changes

**Comment by ciampix** [comment]
Ok you are the expert, you decide. If that is a better term, just change the patch...

**Comment by chschlue** [comment]
Should be either `Routingmodus` or `Routing-Modus`
https://deppenleerzeichen.de/darfs-ein-leerzeichen-mehr-sein/
SCNR

**Comment by pointhi** [comment]
@chschlue thx for the hint

**Comment by ciampix** [comment]
Thanks!

**Pull request merged**
