### PR TITLE
Update Polish GUI translation to fix file filters

### PR DESCRIPTION
**Pull request by keruseykaryu**
This updated translation fixes problem with wrong file filters in file open dialogs. KiCad now use string concatenation to manage file extensions filters. Previous translation uses fixed extensions, so internal code create wrong (doubled, for ex. ".liblib") extensions.

Fix for https://bugs.launchpad.net/kicad/+bug/1783508

### CODE REVIEW

**Comment by stambaughw** [comment]
Kerusey,

Your pull request seems way to big for just a few file filter changes.  I'm not sure how this happened but I don't even see your commit for this in your repo.  Please create a fresh clone of the kicad-i18n repo and only change the file filter strings so your pull request only contains these changes.

**Comment by keruseykaryu** [comment]
This will left about one and half thousand phrases untranslated...

5_0_branch_gui_translation

**Comment by nickoe** [comment]
@stambaughw 

Is it not possible in kicad to simply make the regex untranslatable?

Currently the source has something like:
```
wxString PcbFileWildcard()
{
    return _( "KiCad printed circuit board files (*.kicad_pcb)|*." ) +
    FormatWildcardExt( "kicad_pcb" );
}
```
And change to:
```
wxString PcbFileWildcard()
{
    return _( "KiCad printed circuit board files" ) +  wxString( "*.kicad_pcb)|*." ) +
    FormatWildcardExt( "kicad_pcb" );
}
```

**Comment by keruseykaryu** [comment]
I've push full update for master branch. This will definitive close this request. 
Please don't reopen.

**Pull request closed without merging**
