### PR TITLE
Add English translation to allow Unicode characters

### PR DESCRIPTION
**Pull request by GyrosGeier**
This allows Unicode characters in English texts by providing a "translation". The original strings in the program remain ASCII only.

### CODE REVIEW

**Comment by ciampix** [comment]
Sorry, this PR is very old... I probably have waited some comments on this that and just forgot... really sorry. All this apart, honestly, I do not see any point in this patch. If this comes out to be just useless I will close it in a couple of days.

**Comment by nickoe** [comment]
I have not tested this, but I am ok with merging this if it works.  As far as I understand it simply means that we monst of the time for the english "translation" need to update the po file with the same content, except for cases where kicad uses asciiart in the strings?

**Comment by ciampix** [comment]
Yes ... if I have understood rightly... if the po file is not updated, for instance in case of a fuzzy string, the new reference ascii string simply pops up again, so as it used to be ... no big deal ... I'm merging it...

**Comment by GyrosGeier** [comment]
Even better: the "msgen" tool automatically updates the "en" translation for new strings.

**Comment by ciampix** [comment]
Merged...thanks!

**Pull request merged**
