### PR TITLE
Added some more translations and subjective fixes that need to be dis…

### PR DESCRIPTION
**Pull request by timofonic**
Here's my first try at translating some more. I just advanced 5%

I modified some sentences and I don't understand why some words are capitalized like names. Is that OK? I changed some of them, maybe that's intended.

There's some inconsistency about translating some terms: footprint, pads, ratsnest...

pads=isletas? I never used that term, for example.

I needed to learn to deal with .po files and basic git usage. I would love if the Spanish translators that did most of the work can review my little effort, so I can continue at it and improve my workflow. I'm not as skilled as you, but I would love to help at translating KiCad to Spanish.

### CODE REVIEW

**Comment by nickoe** [comment]
@ElektroQuark  FYI. Could you review @timofonic's question?

**Comment by ElektroQuark** [comment]
Hello,

You are working in part of the previous translation.
I am changing "isleta" to "pad" too.
And removing capitalized words where not necessary.

Please, read the first 60% of the .po file, so you can have a view of how translation is being done.
If you start changing words and constructions the translation will be a mess of styles.
That's why I told you to use KiCad with my current translation helping me finding errors and optimizing expressions.

Regards,
Iñigo.

**Comment by jp-charras** [comment]
Le 08/11/2015 20:33, ElektroQuark a écrit :
> Hello,
> 
> You are working in part of the previous translation.
> I am changing "isleta" to "pad" too.
> And removing capitalized words where not necessary.
> 
> Please, read the first 60% of the .po file, so you can have a view of
> how translation is being done.
> If you start changing words and constructions the translation will be a
> mess of styles.
> That's why I told you to use KiCad with my current translation helping
> me finding errors and optimizing expressions.
> 
> Regards,
> Iñigo.

About capitalization, be aware there are some rules, to try to give a
bit of consistency in menus and dialogs:
<kicad_srcs>/documentation/rules_for_capitalization_in_Kicad_UI.txt

(They are imported from Gnome UI)

Thanks,

-- 
Jean-Pierre CHARRAS

**Comment by ElektroQuark** [comment]
On 08/11/2015 20:18, nickoe wrote:
>
> @ElektroQuark <https://github.com/ElektroQuark> FYI. Could you review 
> @timofonic <https://github.com/timofonic>'s question?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/KiCad/kicad-i18n/pull/21#issuecomment-154859154>.
>
Done!

**Comment by timofonic** [comment]
@ElektroQuark 

Thanks to your lightning fast reply!

I don't want to make it a mess of styles. I didn't see the point of capitalized words and I was changing translations in a fast way. This was more a test than a final effort.

Could we agree on a defined translation style and have formal reasons for that? I know this might add extra work, but it could be interesting for future efforts and other possible contributors.

Should we do a list of electronics terms and agree on how to translate them? I still don't see clear the best translations for "footprint" (patillaje? it sounds a bit fuzzy to me) and "ratsnest" are.

I was writing this before Jean-Pierre Charras replied, now I see there's some rules for capitalization:

- Could these be added to the translation documentation instead only a .txt? 
* I did look at [http://docs.kicad-pcb.org/en/gui_translation_howto.html The GUI translation howto] with some assitance and modified the .po file by learning how to do basic Git usage.

- I have the impression the howto should be updated a bit, or put some things more easy to understand. A very basic Git introduction could be useful to novices without VCS experience such as me ;)

**Comment by nickoe** [comment]
@ElektroQuark  and @timofonic   please align on your efforts. FYI, Wayne has been talking about calling a kicad 4.0.1 pretty soon, so it would be nice if you could reach 100% percent by that time.

**Comment by ElektroQuark** [comment]
On 08/12/2015 20:19, nickoe wrote:
>
> @ElektroQuark <https://github.com/ElektroQuark> and @timofonic 
> <https://github.com/timofonic> please align on your efforts. FYI, 
> Wayne has been talking about calling a kicad 4.0.1 pretty soon, so it 
> would be nice if you could reach 100% percent by that time.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/KiCad/kicad-i18n/pull/21#issuecomment-162987304>.
>
Hi,

As far as I know timofonic is not working any more in the translation 
after his first attempt.
I'm working in the translation, optimizing translated texts and adding 
new translations.
The last commit is pending for some days. Git gives an error but I can 
find what it is, I think it must be something about the timfonics 
commit, but I can find time to learn Git at this moment.

I know about the 4.0.1 update, but my free time is very limited. I'm 
sorry very much. I will try to spend some more time with KiCad Spanish 
translation.

Iñigo.

**Comment by nickoe** [comment]
I will close this pull request, and then you can rebase your change in the other pull request.

**Pull request closed without merging**
