### PR TITLE
Update Portuguese translation

### PR DESCRIPTION
**Pull request by heitorPB**
With KiCad 5.1.4
commit c3dc1f65d449ca56b6d4d1b96dd8bbdd95d306aa

or should I update the po file with current master of KiCad, instead 5.1.4 tag?

### CODE REVIEW

**Comment by francisco-pereira** [comment]
Hello @heitorPB,

Are you translating into Brazilian Portuguese or European Portuguese?
If it's Brazilian Portuguese we should join efforts, as I 'm already translating it too.
If it's European Portuguese, I think we should ask the developers to split the current translation "pt", into "pt_PT" and "pt_BR" so there is no conflict.

As for your commit, I think the 5.1.4 version was already tagged and new translations will probably go to a future 5.1.5 tag. In this case you should translate from the 5.1 branch.

**Comment by heitorPB** [comment]
Hello @francisco-pereira,

I'm translating into Brazilian Portuguese. We should definitely join efforts! Is there a place to discuss translations? Is it the dev mailing list?

I guess I screwed up where my branch started. I'll try to rebase this week with 5.1 branch

**Comment by francisco-pereira** [comment]
@heitorPB,

There is a mailing list http://kicad-pcb.org/contribute/docs-team/, but I think they use it mainly for discussing documentation issues.
I think we can start talking by e-mail for now: frosch underline bin at yahoo dot com dot br

**Comment by ciampix** [comment]
May I merge this then?

**Comment by francisco-pereira** [comment]
For me it seems ok to merge.

**Comment by ciampix** [comment]
ok then, thank you!

**Pull request merged**
