### PR TITLE
de: Update whole translation to current version

### PR DESCRIPTION
**Pull request by tijuca**
I'm using KiCad from the current Debian unstable repository. The version in the Debian archive is 4.0.0-rc1and not the recent upstream version 4.0.1. But the translation for German isn't working that much now. This depends on the state of the de/kicad.po as there are most of the string are fuzzy, unclear or not translated, there are only a few strings working.

I updated the kicad.po file as most as possible and it's working locally fine as I could see. Please pull my changes so the translation will be up to over 95% I would say.

### CODE REVIEW

**Comment by ciampix** [comment]
Many thanks!
Do you want to volunteer for the translation of the Getting started in KiCad in German also? That document is completely without any German translation...

**Comment by tijuca** [comment]
Thanks!
I was thinking about that. I'm stumbling with the needed creation of the respective files locally. The instructions on https://github.com/KiCad/kicad-doc/blob/master/translation_instructions.adoc seems to be wrong or outdated. 
If possible just add the needed files for the German translation, I will pull them and start to work on it.

**Comment by ciampix** [comment]
Ok I will do it in minutes...I'll try to update the translation instructions too but later...

**Comment by ciampix** [comment]
Ok now update the addendum.de and po/de.po (header first) in src/getting_started_in_kicad/po/. Good translation!

**Comment by ciampix** [comment]
I'll be away for a couple of hours ...

**Comment by tijuca** [comment]
Thanks, will start to work on it.

**Pull request merged**
