### PR TITLE
de: corrections and improvements

### PR DESCRIPTION
**Pull request by roybaer**
- German spelling prohibits whitespace in compound nouns => use concatenation or hyphenation
- replace some clumsy literal translations
- rearrange sentences with odd word order
- some other fixes

### CODE REVIEW

**Comment by tijuca** [comment]
The fixes are fine, thanks for fixing still existing issues, the commit message should be improved to be a valid Git commit message.

This is the native commit message:
```
$ git show a6a94b539fa2746112aa20e2f39e6711e56fabee --check 
commit a6a94b539fa2746112aa20e2f39e6711e56fabee (roybear/master)
Author: Benedikt Freisen <b.freisen@gmx.net>
Date:   Sun Oct 22 14:07:39 2017 +0200

    de: corrections and improvements
    - German spelling prohibits whitespace in compound nouns => use concatenation or hyphenation
    - replace some clumsy literal translations
    - rearrange sentences with odd word order
    - some other fixes
```
And this is what Git is doing with this commit message as online output (only the subject line should be visible):
```
$ git show a6a94b539fa2746112aa20e2f39e6711e56fabee --oneline --check 
a6a94b5 (roybear/master) de: corrections and improvements - German spelling prohibits whitespace in compound nouns => use concatenation or hyphenation - replace some clumsy literal translations - rearrange sentences with odd word order - some other fixes
```
This is hard to read, but can be easy fixed as the intended message itself is o.k.. The first line is the subject and that's o.k. After that just add a empty line so that beginning with the 3rd line the additional message is starting. The second line is always empty.

https://chris.beams.io/posts/git-commit/

**Comment by roybaer** [comment]
Alright.  I was not aware of any such convention.  Fixed.

**Comment by ciampix** [comment]
Is it ok to commit this patch for now? I'll do it right now if you both agree...

**Comment by roybaer** [comment]
No objections from my side.

**Comment by tijuca** [comment]
@ciampix 
It's fine, just go ahead.

@roybaer 
I have no hard objections on one or the other term(s) nor I work in that business. We need also to consider to make it consistent in all of to the various documentation files in kicad-doc too then. I didn't have take the time in the past to take a special look at this all due a lot of other things I do. So I've just tried to get all documents translated near 100%, but this for the stable 4.0 and the nightly release of KiCad and the documentation too. The documentation for the upcoming 5.0 release needs some love now again.

**Comment by ciampix** [comment]
Ok thanks to all

**Pull request merged**
