### PR TITLE
fix: compile fail with -DCMAKE_INSTALL_PREFIX

### PR DESCRIPTION
**Pull request by liyoubdu**
the kicad-root-dir should include sub-dir 'usr/local'.

### CODE REVIEW

**Comment by jp-charras** [comment]
I don't think the change:
KICAD_I18N_PATH ${CMAKE_INSTALL_PREFIX}/usr/local/share/locale
is correct.
CMAKE_INSTALL_PREFIX is (or should be) already defined as /usr or /usr/local

**Comment by liyoubdu** [comment]
why

**Comment by ciampix** [comment]
I also (like @jp-charras) am curious on why we should specify the locale position given that cmake is able to figure it out correctly by itself...

**Comment by liyoubdu** [comment]
well, where is the script which we use to generate the installation package.

**Comment by ciampix** [comment]
where is such a script? May I take a look at it?

**Comment by nickoe** [comment]
@liyoubdu  The changes to the `CMakeLists.txt` is plain wrong as described by jp earlier.

I don't see the changes to the README makes it better.

**Pull request closed without merging**
