### PR TITLE
Full Polish GUI translation (From master branch)

### PR DESCRIPTION
**Pull request by keruseykaryu**
This is the full update. About 1600 strings translated or updated to remove "fuzzies". Sources taken from recent master branch of _KiCad/kicad-source-mirror_ repository.
Folders `new` and `resources` have been excluded from translation. I don't know if they could be translated.

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by ciampix** [comment]
Mmm just checked now ... why translating master and leave the stable branch untranslated? Are you aware that stable is in string freeze and instead master is a moving target?

**Comment by keruseykaryu** [comment]
I have the translation for stable 5.0, but I couldn't get along with Wayne about that in my closed commit #296

**Comment by ciampix** [comment]
Ok I'llsee to that... be patient ... I'm out of home now...

**Pull request merged**
