### PR TITLE
my last work

### PR DESCRIPTION
**Pull request by ok1rr**
bigger update of czech translation

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by ciampix** [comment]
Please be aware that this is master (dev - unstable) branch ... not the 5 (stable - current) branch ... perhaps you want to update also that (5) branch? If you want that I update the strings _before_ you start translating them, please let me know and I'll do an update immediately basing them on current source strings ...

**Comment by ok1rr** [comment]
Hi, yes, it would be nice to update both branches. Let me know what I should do, I would do it immediately. Now fully retired so I returned to the project which I initiated 10 years ago...

**Comment by ciampix** [comment]
I can try to do a "cherry-pick" (see: https://git-scm.com/docs/git-cherry-pick) and apply your update to  also the stable branch (5) and then update it so you can finish translating it. I would not update the master branch since it is a dev branch so it changes very often...

**Comment by ok1rr** [comment]
Many thanks, Marco! Grazie!

**Comment by ciampix** [comment]
I was unable to cherry-pick it but committed anyway and updated from sources accordingly: see commit e4281aaae99c1ac632d0cbdec1628452123bfe27

**Pull request merged**
