### PR TITLE
Translation at 46%

### PR DESCRIPTION
**Pull request by ElektroQuark**
Still work in progress.
From 38% to 46% now.

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by timofonic** [comment]
You're really fast! Thanks for your effort :D

I want KiCad translated in Spanish to promote it in vocational schools and
such. Am I able to do at least some contribution to the translation? If
transifex approach is cumbersome, I can use any other procedure.

I had some issues (again) so my productivity is a lot worse than yours, But
I can to collaborate on it, at least to get some experience on translating.

I hope to be more avilable the next week. I don't promise to be able to do
something for this week because pending homework is getting bigger, but
I'll do efforts to finish the boring stuff and have some available time for
this and other personal projects ;)

**Comment by ElektroQuark** [comment]
On 29/10/2015 0:08, timofonic wrote:
> You're really fast! Thanks for your effort :D
>
> I want KiCad translated in Spanish to promote it in vocational schools and
> such. Am I able to do at least some contribution to the translation? If
> transifex approach is cumbersome, I can use any other procedure.
>
> I had some issues (again) so my productivity is a lot worse than 
> yours, But
> I can to collaborate on it, at least to get some experience on 
> translating.
>
> I hope to be more avilable the next week. I don't promise to be able to do
> something for this week because pending homework is getting bigger, but
> I'll do efforts to finish the boring stuff and have some available 
> time for
> this and other personal projects ;)
>
> On Wed, Oct 28, 2015 at 2:34 PM, Marco Ciampa <notifications@github.com>
> wrote:
>
> > Thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/KiCad/kicad-i18n/pull/13#issuecomment-151846139>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/KiCad/kicad-i18n/pull/13#issuecomment-152024471>.
>

Hi,

You can help the translation process using KiCad with partial 
translations and sending me errors and change proposals.
I really need some people using it and giving feedback.
Thank you.

Iñigo.

**Comment by timofonic** [comment]
Hello.

I try to use English in computing and every other aspect of my life, the
reason is to force myself to improve my English skills. But I'm going to
switch to Spanish locale in KiCad for testing purposes.

Do you put your translations early in your public Git branch and sync it
with main branch often too? I use Arch Linux, I can modify kicad-bzr AUR to
point to your Git repo. This way, I can use the latest KiCad with your
latest translation and provide modifications if I'm able to learn basic
GitHub pull requests or suggest them to you.


I have big interest in 100% Spanish i18n:

- Website: Translate all content in Spanish, even future news.
- Documentation: I'm interested in translating documentation, specially the
one assumed at users. Can this be made easier by providing a wiki-like
approach?
- Tutorials and videos
* Written form: As with documentation, I would love to be able to have a
working infraestructure aiming to have constantly updated information up to
the latest KiCad and sync translations of that content.
* Scripting (recording a KiCad session to be "played" into KiCad itself):
If/When scripting capabilities are ready for that, a KiCad session can be
recorded as with Tool Assisted Speedruns in videoconsole emulators.
** This would be relatively release dependent if API and user interface
changes, so this would probably require a strong community to maintain
them: The advantages are better integration into KiCad itself, dramatically
smaller file sizes and more optimized showing by editing actions.
** Subtitles, notes, dubs, images and overlay videos could be used to
provide detailed explainings.
* Dubbing: For complete i18n, I think we would need at least to have
professional quality dubbers.  This isn't easy to have:
** I consider amateur ones usually not enough attractive and motivating to
users.
** Text-to-Speech (Loquendo is quite common in Spanish) is totally boring
and umotivating most of the time. I believe emotionless speech to be very
unmotivating and boring, maybe others may agree on this.
- Community: kicad-es is dead. Enough skilled people is able to have an
okaish English level. There's no Spanish forum about KiCad. Communities in
other countries are quite segmented and lack of activity, but the Japanese
one seems active.


Kind regards.

**Comment by ElektroQuark** [comment]
On 02/11/2015 22:00, timofonic wrote:
> Hello.
>
> I try to use English in computing and every other aspect of my life, the
> reason is to force myself to improve my English skills. But I'm going to
> switch to Spanish locale in KiCad for testing purposes.
>
> Do you put your translations early in your public Git branch and sync it
> with main branch often too? I use Arch Linux, I can modify kicad-bzr 
> AUR to
> point to your Git repo. This way, I can use the latest KiCad with your
> latest translation and provide modifications if I'm able to learn basic
> GitHub pull requests or suggest them to you.
>
>
> I have big interest in 100% Spanish i18n:
>
> - Website: Translate all content in Spanish, even future news.
> - Documentation: I'm interested in translating documentation, 
> specially the
> one assumed at users. Can this be made easier by providing a wiki-like
> approach?
> - Tutorials and videos
> * Written form: As with documentation, I would love to be able to have a
> working infraestructure aiming to have constantly updated information 
> up to
> the latest KiCad and sync translations of that content.
> * Scripting (recording a KiCad session to be "played" into KiCad itself):
> If/When scripting capabilities are ready for that, a KiCad session can be
> recorded as with Tool Assisted Speedruns in videoconsole emulators.
> ** This would be relatively release dependent if API and user interface
> changes, so this would probably require a strong community to maintain
> them: The advantages are better integration into KiCad itself, 
> dramatically
> smaller file sizes and more optimized showing by editing actions.
> ** Subtitles, notes, dubs, images and overlay videos could be used to
> provide detailed explainings.
> * Dubbing: For complete i18n, I think we would need at least to have
> professional quality dubbers. This isn't easy to have:
> ** I consider amateur ones usually not enough attractive and motivating to
> users.
> ** Text-to-Speech (Loquendo is quite common in Spanish) is totally boring
> and umotivating most of the time. I believe emotionless speech to be very
> unmotivating and boring, maybe others may agree on this.
> - Community: kicad-es is dead. Enough skilled people is able to have an
> okaish English level. There's no Spanish forum about KiCad. Communities in
> other countries are quite segmented and lack of activity, but the Japanese
> one seems active.
>
>
> Kind regards.
>
> On Thursday, October 29, 2015, ElektroQuark <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > On 29/10/2015 0:08, timofonic wrote:
> > > You're really fast! Thanks for your effort :D
> > >
> > > I want KiCad translated in Spanish to promote it in vocational schools
> > and
> > > such. Am I able to do at least some contribution to the 
> translation? If
> > > transifex approach is cumbersome, I can use any other procedure.
> > >
> > > I had some issues (again) so my productivity is a lot worse than
> > > yours, But
> > > I can to collaborate on it, at least to get some experience on
> > > translating.
> > >
> > > I hope to be more avilable the next week. I don't promise to be 
> able to
> > do
> > > something for this week because pending homework is getting 
> bigger, but
> > > I'll do efforts to finish the boring stuff and have some available
> > > time for
> > > this and other personal projects ;)
> > >
> > > On Wed, Oct 28, 2015 at 2:34 PM, Marco Ciampa 
> <notifications@github.com>
> > > wrote:
> > >
> > > > Thanks!
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > 
> <https://github.com/KiCad/kicad-i18n/pull/13#issuecomment-151846139>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/KiCad/kicad-i18n/pull/13#issuecomment-152024471>.
> > >
> >
> > Hi,
> >
> > You can help the translation process using KiCad with partial
> > translations and sending me errors and change proposals.
> > I really need some people using it and giving feedback.
> > Thank you.
> >
> > Iñigo.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/KiCad/kicad-i18n/pull/13#issuecomment-152092201>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/KiCad/kicad-i18n/pull/13#issuecomment-153155142>.
>
The main sources of KiCad are in synch with my translation. Just 
download the lastest version.

We can manage the KiCad Spanish forum, I can publish one at my homepage, 
if there is some interest.

**Comment by ciampix** [comment]
I have just produced a small script that is able to update all template (po) files in one time. The aim is to run it from time to time to have the .po files automatically updated periodically. This could enable a web translation interface in the future. Hope you will appreciate this.

**Pull request merged**
