### PR TITLE
This is new translate

### PR DESCRIPTION
**Pull request by amudas**
Updated GUI Chinese language

### CODE REVIEW

**Comment by nickoe** [comment]
@amudas Thank you, but I get too errors when I try to build the translations:
```
po:10401: 'msgid' and 'msgstr' entries do not both begin with 'n'
po:23033: 'msgid' and 'msgstr' entries do not both end with 'n'
```
I am using the `update-po-files.sh` script.

It looks like there is some issues with the newlines, see this comment, https://github.com/daid/Cura/issues/992#issuecomment-60504053.

Please try to fix this.

I tried to blindly fix it locally and got:
## zh_CN
4916 translated messages
3 fuzzy translations
1 untranslated message

So you are almost on 100% yay

**Comment by nickoe** [comment]
Ok, I assume these match the product branch of KiCad and I will try my best to merge these to 4.0 too.

**Comment by amudas** [comment]
Thank you! I use POEDIT, Perhaps this is a problem generated by the software.

**Comment by nickoe** [comment]
Poedit should be fine, but you should run the validation that it has to make sure that it compiles. I have merged it on the master and run the update script against the kicad product branch and I have merged it to 4.0 and run the update script agaist the 4.0 branch. 

So chinese is in pretty good shape now.

**Pull request merged**
