### PR TITLE
de: update po file after upstream changes

### PR DESCRIPTION
**Pull request by tijuca**
Not a final state but lower down the count of untranslated strings to quite zero. Some strings need to be adjusted after reviewed in the GUI.

### CODE REVIEW

**Comment by nickoe** [comment]
Even though you say that it is not in final stage, do you still wnt it merged now or not?

**Comment by nickoe** [comment]
Even though you say that it is not in final stage, do you still wnt it merged now or not?

**Comment by tijuca** [comment]
The commit is fine enough to get merged. There will be some small parts that will need same modifications to provide a better readability.
For now I have better a translation at all instead of no translated strings. This also takes the barrier low for contributors that wont do a big work.

**Comment by nickoe** [comment]
Good, thanks.

**Pull request merged**
