### PR TITLE
Update simplified chinese translation

### PR DESCRIPTION
**Pull request by taotieren**
Update simplified chinese translation

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by taotieren** [comment]
@ciampix I want to add Simplified Chinese translator information to kicad (launchpad.net/kicad). I tried to use the bzr repository manager of launchpad. I didn't find the manual and instructions for using bzr on launchpad. I don't know how to put me. The submitted information is patched and merged into the warehouse of kicad (launchpad.net/kicad). Or can I help me add simplified Chinese translator information to kicad(launchpad.net/kicad)?

**Comment by ciampix** [comment]
Why bzr? It is not used anymore...

**Comment by taotieren** [comment]
Launchpad prompts me to use bzr, so how does kicad (launchpad. net / kicad) manage on launchpad?

**Pull request merged**
