### PR TITLE
Update German to 5.1 bug 463

### PR DESCRIPTION
**Pull request by Jan-vi**

### CODE REVIEW

**Comment by ciampix** [comment]
Thanks!

**Comment by tijuca** [comment]
You are sure that MR was right? At least the file is now in the wrong folder.

**Comment by ciampix** [comment]
You are right, I've checked it cursory, sorry ... github doesn't show clearly a file move/add. I'll reverse it immediatly...

**Comment by Jan-vi** [comment]
@tijuca This is my 1st contribution to github and I also wondered about the diffrences. I have used poedit for windows and this should not change all lines cr/lf. I also opened a local branch and merged this before to see conficts and probably it happened thereby?
Nevertheless somebody else changed this issue for the master already partitially but other things around there are shuffeld and need changes to complete why its indispensible to understand what went wrong.

**Pull request merged**
