### PR TITLE
Update kicad_zh_CN_v5.1.1.003

### PR DESCRIPTION
**Pull request by taotieren**

### CODE REVIEW

**Comment by nickoe** [comment]
It looks like you made this commit against kicad-i18n master branch, but it should be against the 5.1 branch.

**Comment by taotieren** [comment]
Where is the 5.1.1 branch submitted?

**Comment by ciampix** [comment]
Go to https://github.com/KiCad/kicad-i18n and select the correct branch...

**Comment by nickoe** [comment]
The 5.1.1 is a tag of the kicad source code.

The 5.1 branch is: https://github.com/KiCad/kicad-i18n/tree/5.1

You should be able to do something along the lines of:
```
cd kicad-i18n
git fetch origin
git checkout origin/5.1
<update your po file against the kicad source checked out to the 5.1.1 tag>
git add zh_CN
git commit
git push taotiren
```

**Comment by taotieren** [comment]
thanks

**Comment by nickoe** [comment]
@taotieren If I take this an apply it for the 5.1 branch I get:

```
## zh_CN
5547 translated messages
55 fuzzy translations
4 untranslated messages
```

**Comment by taotieren** [comment]
I tested it on kicad-git, the display is normal, the layout is normal, and more details have not been tested.

**Comment by taotieren** [comment]
@nickoe  Some words can be retained without translation, and several of them are not sure what to translate, and the original intention is not translated. Please use kicad_zh_CN_v5.1.1.004.po

**Comment by taotieren** [comment]
I tested the normal display on kicad-5.1.0-276-g4d3e86d79.

**Pull request closed without merging**
