### PR TITLE
The symbol pin electrical type cannot display Chinese, restore these strings to English.

### PR DESCRIPTION
**Pull request by CNLiuGuang**

### CODE REVIEW

**Comment by ciampix** [comment]
Mmm would you pleas take a screenshot of this? It could be filed (if you already didn't do that) as a bug to the developers. In the mean time I merge this...

**Comment by ciampix** [comment]
Thanks as usual!

**Comment by CNLiuGuang** [comment]
Hi
   Previously the developer replied.
Version 6 Road Map  -----  Allow Use of System Fonts






At 2018-09-17 13:49:23, "Marco Ciampa" <notifications@github.com> wrote:


Mmm would you pleas take a screenshot of this? It could be filed (if you already didn't do that) as a bug to the developers. In the mean time I merge this...

**Comment by CNLiuGuang** [comment]
Attach a bug screenshot





在 2018-09-17 14:39:48，"Liu Guang" <l.g110@163.com> 写道：

Hi
   Previously the developer replied.
Version 6 Road Map  -----  Allow Use of System Fonts






At 2018-09-17 13:49:23, "Marco Ciampa" <notifications@github.com> wrote:


Mmm would you pleas take a screenshot of this? It could be filed (if you already didn't do that) as a bug to the developers. In the mean time I merge this...

**Comment by CNLiuGuang** [comment]
cn_pin type

**Comment by CNLiuGuang** [comment]
snipaste_20180917_145211

This is the previous mail message

**Comment by ciampix** [comment]
Doh! Ok, thanks!

**Pull request merged**
