### PR TITLE
de: update POT file against tag 4.0.3

### PR DESCRIPTION
**Pull request by tijuca**
After picking up the correct branch here is another pull request against/for the 4.0 branch of kicad-i18n. Happily PoEdit has done most of the job and I could quickly collect the new needed translation strings.

### CODE REVIEW

**Comment by nickoe** [comment]
@tijuca Hi, I see that there are still quite a bit if translations missing, mostly related to the hotkeys. You should try to add the translation keyword `_HKI` to your po editor. Also you probably need to check that you are searching the dirs shown in the POTDIRS file. Thanks.

**Comment by tijuca** [comment]
@nickoe 
Thanks to your suggests about adding the additional keyword to PoEdit I picked up (hopefully all) the missed translation strings for German now. The source inclusion inside PoEdit for bitmap2component/ was also still missed.
Please give it a new try. Thanks!

**Comment by nickoe** [comment]
It looks like the only thing missing is to include the include directory :)

**Comment by tijuca** [comment]
Yeah, I've added the `include/` directory too and now it should be o.k. The helper script is happy now.
```
 $ ./update-po-files.sh de
Using default SOURCEDIR=../kicad-source-mirror
Writing summary to /home/tijuca/gitprojects/kicad-i18n/i18n_status.csv
## de
4920 translated messages
```
No more fuzzy or untranslated strings.

**Comment by nickoe** [comment]
Thank you very much!

**Pull request merged**
