### PR TITLE
Translation of Chinese is 100% finished

### PR DESCRIPTION
**Pull request by cdhigh**

### CODE REVIEW

**Comment by nickoe** [comment]
Thank you, I see you updated the translations for the master branch and not the 4.0 branch. Becasue when I compare to the 4.0 branch I see 4 fuzzy translations and 1 untranslated message, while for the master there is no fuzzy or untranslated messages. :)

Do you understand what I mean when I mention the 4.0 branch?

I will merge this to the master branch.

**Comment by yoneken** [comment]
Excellent work!

**Comment by cdhigh** [comment]
Actually, the translations was been synchronized with source of branch 4.0, and then you can merge it to 4.0 manualy?

**Comment by nickoe** [comment]
@cdhigh yes, I have already merged it ot the 4.0 branch in https://github.com/KiCad/kicad-i18n/commit/64b0cbba0b557453f6242d4b37155d311758b485 but still there are a few string that needs attention. There are now:
## zh_CN
4915 translated messages
4 fuzzy translations
1 untranslated message

On the 4.0 branch.

But I would like you to reveiw this
message:

```
23809 #: include/richio.h:220
23810 #, c-format
23811 msgid ""
23812 "KiCad was unable to open this file, as it was created with a
more recent "
23813 "version than the one you are running. To open it, you'll need
to upgrade "
23814 "KiCad to a more recent version.\n"
23815 "\n"
23816 "Date of KiCad version required (or newer): %s\n"
23817 "\n"
23818 "Full error text:\n"
23819 "%s"
23820 msgstr ""
23821 "KiCad无法打开此文件，因为该文件由一个较新的版本创建。要打开它，请升级到KiCad"
23822 "的最新版本"
```

It looks like this is missing some newlines and some format specifiers (%s).

**Comment by cdhigh** [comment]
In my pull request, it was fixed, I don't known which version you mentioned.

Attached it.

2016-08-05 5:35 GMT-03:00 nickoe <notifications@github.com>:

**Pull request merged**
