### PR TITLE
de: update po file after upstream changes

### PR DESCRIPTION
**Pull request by tijuca**
Also including extra keyword '_T' in PoEdit which shouldn't normaly be
used any longer.  Just to get these strings to that covered by this
macro.

### CODE REVIEW

**Comment by ciampix** [comment]
Sorry I do not understand. Are these _T strings used or not? If it is so, I think we  better add this prefix into all others .po files as well...

**Comment by tijuca** [comment]
I was bringing the usage of that keyword to discussion on the ml of kicad-doc-devs some days ago.

https://lists.launchpad.net/kicad-doc-devs/msg00014.html

Wayne has removed those old keywords already and I updated my commit right now. So back to normal, no added extra keyword to the Keyword list of PoEdit and no need to update the other po files.

**Comment by ciampix** [comment]
Many thanks @tijuca! I also discovered to have disabled (I wonder how I did... doh!) the email commit from the kicad-doc-dev so this passed without I noticed it. So, may we close this PR? Do you still need this merge?

**Comment by tijuca** [comment]
This PR is still valid as I rebased my work on the latest changes from upstream yesterday were those '_T' keywords are now history. So yes, please pull.

**Comment by ciampix** [comment]
Thanks!

**Pull request merged**
