### PR TITLE
[Russian] Lot of the improvements.

### PR DESCRIPTION
**Pull request by baranovskiykonstantin**
Russian translators can get information about all changes here:
http://electronix.ru/forum/index.php?showtopic=126971

### CODE REVIEW

**Comment by eldarkg** [comment]
Hello. Some fixes in patch.
[small-fixes.patch.txt](https://github.com/KiCad/kicad-i18n/files/257829/small-fixes.patch.txt)
Look it, maybe somewhere I am wrong.
Look at somewhere "посад.место" and somewhere "посадочное место". It's so conceived?

**Comment by baranovskiykonstantin** [comment]
@eldarkg, hello!
Extra spaces was discussed on forum (see link above). I'm not sure that whitespace is a good splitter in that case. Maybe we need some different symbol (";" for example)? Please, join to us on forum and together we will make i18n and doc better.
Some comment about "посад.место" and "посадочное место". 
Reductions is hard to perceive, so it left only in places where small available space (menu items, toolbars, etc.). In all other cases strongly recommended to use full words without any reductions.
I will apply the next change from your patch:

```
 msgid "3D configuration directory is unknown"
-msgstr "Каталог конфигурации 3D неизвестна"
+msgstr "Каталог конфигурации 3D неизвестен"
```

But we need to discuss all other changes.
```
 msgid "Align bottom"
-msgstr "По верхнему краю"
+msgstr "По нижнему краю"
 ```
and
```
 msgid "Align top"
-msgstr "По нижнему краю"
+msgstr "По верхнему краю"
```
This strings translated to fit the behavior (you can verify it in Eesctema by changing settings of the text item).

**Comment by eldarkg** [comment]
@baranovskiykonstantin 
You say: "Extra spaces was discussed on forum (see link above). I'm not sure that whitespace is a good splitter in that case. Maybe we need some different symbol (";" for example)?"
Answer: I agree. I was translating the UI that it will be nearly as original. It need fixed in future.

You say: "Some comment about "посад.место" and "посадочное место". 
Reductions is hard to perceive, so it left only in places where small available space (menu items, toolbars, etc.). In all other cases strongly recommended to use full words without any reductions."
Answer: OK.

You say: "This strings translated to fit the behavior (you can verify it in Eesctema by changing settings of the text item)."
Answer: OK.

"Please, join to us on forum and together we will make i18n and doc better."- I don't like forums. Maybe it is right to create "Issue" in this repo for discussion RU i18n (on Russia language)? And give link to the forum to here.

**Comment by eldarkg** [comment]
Thanks to all who had taken part in creation this request

**Pull request merged**
