### PR TITLE
4.0

### PR DESCRIPTION
**Pull request by RendszergazdaNyh**
Hello!

I have just registered here and do not understand how this site works.
I translated the KiCad 4.0.7 software into Hungarian version and would like to publish the language file. How can I do this?

### CODE REVIEW

**Comment by ciampix** [comment]
This is a mess.

Sorry I have to close this without any commit. For the time being send the translation file to me or to the mailing list and I'll see to test it and commit it.

**Comment by ciampix** [comment]
I suggest you to try and do some git experiments on some test files before trying it on "live" projects.

**Comment by RendszergazdaNyh** [comment]
A Hungarian-language file was released for version 4.0.7 as the first release.If you would like to use it, please read the Information.pdf file.
Language files (kicad.mo) and information (Information.pdf) include the compressed file.You can use the KiCAD 4.0.7 Hun GUI 1.1.sfv file to verify that the compressed file is flawless,which must be started in a total commander file manager...
RendszergazdaNyh
-- Eredeti üzenet --
Feladó: Marco Ciampa&lt;notifications@github.com&gt;Címzett: KiCad/kicad-i18n&lt;kicad-i18n@noreply.github.com&gt;Elküldve: 2018. március 4. 16:58Tárgy : Re: [KiCad/kicad-i18n] 4.0 (#228)


This is a mess.
Sorry I have to close this without any commit. For the time being send the translation file to me or to the mailing list and I'll see to test it and commit it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  






_________________________________________

Citromail.hu levelezőrendszerből küldve

Lépj be vagy regisztrálj

; Generated by WIN-SFV32 v1.0
; (Compatible: Total Commander 8.0)
KiCAD 4.0.7 Hun GUI 1.1.zip 42DBBFE0

**Comment by ciampix** [comment]
Sorry but the file you sent cannot be used. You sent a binary (.mo) version of the translated messages instead of the source version (.po). Please read this guide: http://docs.kicad-pcb.org/master/en/gui_translation_howto.html

**Pull request closed without merging**
