### PR TITLE
Update KiCad_zh_CN_v5.1.1.006

### PR DESCRIPTION
**Pull request by taotieren**
- Fix some typesetting problems
- Fixing some translation problems

### CODE REVIEW

**Comment by taotieren** [comment]
@ciampix How to submit pull to tag 5.1.1

**Comment by ciampix** [comment]
Done, thanks!

**Comment by taotieren** [comment]
@ciampix Why is kicad_zh_CN of tag5.1.1 not updated synchronously?

**Comment by itviewer** [comment]
@taotieren @ciampix  Forgot run `./update-po-files.sh` ?

Some translations did not take effect. 
```
 ./update-po-files.sh zh_CN
Using default SOURCEDIR=../kicad-source-mirror
Writing summary to /home/itviewer/kicad/kicad-i18n/i18n_status.csv
## zh_CN
5547 translated messages
55 fuzzy translations
4 untranslated messages
```
I have update translations from kicad tag 5.1.1 and fixed it, is it possible submit it to tag 5.1.1?

**Comment by ciampix** [comment]
A tag is a tag. It is fixed in specific position (hash). It is used to let packagers freeze a specific situation in a specific time window. If we move it IMHO it loses its meaning. I prefer to let decide @nickoe since it is him that did the tag/branch things until now.

**Comment by poeschlr** [comment]
I fear it is too late for 5.1.1 as the packages are already in the process of being created. (the deatline was known for more than a week.) See mailing list: 
https://lists.launchpad.net/kicad-developers/msg40178.html

**Comment by itviewer** [comment]
Perhaps the translation file should not be strictly tied to the release version of kicad, so that it can give the translator a chance to improve translation quality later.

**Comment by poeschlr** [comment]
This would significantly increase the effort required for packagers. We might even loose OSx support if nobody steps up and helps out with the release cycle as it is now. (In fact i believe there never was a 5.0.2 release that did not get retracted later.)
For the time being simply accept that kicad has strict deadlines for its release cycle. 

You could have influenced this over at the mailing list by asking for an extension before the packagers started. (I have been the reason why the release got out nearly one week later than wayne planned. Simply because i informed the everyone by posting to the mailing list that i do not have time to check the libraries in time for the original plan. Everyone in the translation team had the same option.)

**Comment by nickoe** [comment]
@itviewer if you have a fix, please submit it for the 5.1 branch. Then it will be included with kicad 5.1.2 which will probably be made not too far into the future. And hopefully the difference between 5.1.1 and 5.1.2 are mostly zero string changes.

Generally the kicad source is tagged first, for a major release multiple time with release candidate tags "-rc1" for example. Translators should then use those or the appropriate branch to submit translations on the approipate kicad-i18n branch. After a while, maybe a couple of weeks the kicad-i18n is tagged and a release can be made.  Library and documentation is tagged in a similar way. I don't think we need to change much here other than document it a bit better in the dev docs.

**Comment by taotieren** [comment]
@itviewer I just re-translated it. https://github.com/KiCad/kicad-i18n/pull/393

**Pull request merged**
