### PR TITLE
Problem

### PR DESCRIPTION
**Pull request by ElektroQuark**
Same error. I have deleted local repo, created again, make changes to Spanish translation but the error shows again.
Marco, can you tell me how do you update your changes? I must be doing something wrong but I'm stuck.

### CODE REVIEW

**Comment by ciampix** [comment]
For a start: why are you changing files that are of your language? Please can you tell us what are the exact commands are you typing in here?

**Comment by ElektroQuark** [comment]
I'm only changing the Spanish .po file.

Commands:

git reset --hard upstream/master
git pull --rebase
git push --force

Then I change es/kicad.po file on local repo

git add es/kicad.po
git commit -m "es updated to 18/05/03"
git push

**Comment by ciampix** [comment]
It seems to me that you are missing git fetch and that reset is not really useful. You should do:
git fetch upstream # _now_ you are fetching the master branch
# and then rebase locally (if you did not make any change locally, this does nothing)
git rebase upstream/master

**Comment by ciampix** [comment]
You modified the spanish .po file but you are still trying to commit on to 5 files... I suggest you to save your translation (kicad.po) in a different place on your disk, then delete your branch. Then recreate your branch and do as I suggest, apply your file, update the .po file, check if there are some more strings to translate and then ask for a pull...

**Comment by ElektroQuark** [comment]
I will delete Github and local branchs and start again.
Can you please elaborate de complete command sequence I must use?
Thank you very much.

**Comment by ciampix** [comment]
I am closing this...

**Pull request closed without merging**
